# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here!
  
  <br>
  **Say Hi on** [Twitter](https://twitter.com/debraj_010) ğŸ‘‹
  <br>
  
  [![Twitter FOLLOW](https://img.shields.io/twitter/url/https/twitter.com/debraj_010.svg?style=social&label=Follow)](https://twitter.com/debraj_010)&nbsp;
  [![LinkedIn URL](https://img.shields.io/badge/Connect-%230077B5.svg?logo=linkedin&style=sociallabel=Connect)](https://www.linkedin.com/in/debrajkarmakar010/)
  <br>


# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! ğŸ¤—
  <br>
  Wishing you a great [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/) ğŸ‰ âš¡
  <br>
  
  ğŸ“¢ Spread the word about [@debrajhyper/Topic_Learning_Resources](https://github.com/debrajhyper/Topic_Learning_Resources) repo across your social media channels to help get others involved!
  <br>
  ğŸ”” **Retweet** [this](https://twitter.com/debraj_010/status/1444397715559833602?s=20).
  <br>
  
  [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/debrajhyper)
  <br>
  
  **Check out few other repos below** ğŸš€
  <br>
  <p align="center" style="display:flex;">
    <a href="https://github.com/debrajhyper/this.weather">
      <img width="370px" src="https://github-readme-stats.vercel.app/api/pin/?username=debrajhyper&repo=this.weather&show_owner=true&show_icons=true&hide_border=true&bg_color=ffffff00&title_color=2e7eff&text_color=878787&icon_color=2e7eff" alt="debrajhyper" />
    </a>

    <a href="https://github.com/debrajhyper/COV-19-India">
      <img width="370px" src="https://github-readme-stats.vercel.app/api/pin/?username=debrajhyper&repo=COV-19-India&show_owner=true&show_icons=true&hide_border=true&bg_color=ffffff00&title_color=2e7eff&text_color=878787&icon_color=2e7eff" alt="debrajhyper" />
    </a>
  </p>
  <br>
  <br>
  **Show some** â¤ï¸
    - Consider leaving a â­ [here](https://github.com/debrajhyper/Topic_Learning_Resources/).
    - Check out more beginner-friendly repos [here](https://github.com/debrajhyper?tab=repositories).
    - Follow @debrajhyper for more updates.
 

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
  <br>
  Wishing you a great [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/) ğŸ‰ âš¡
  <br>
 
  Show some love by starring a few of my [repositories](https://github.com/debrajhyper?tab=repositories).
